version: '2'
services:
  proxy:
    image: jwilder/nginx-proxy:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    expose:
      - "80"
  gitea:
    image: gitea/gitea:1.3.2
    volumes:
      - /data/gitea:/data
    ports:
#      - "22:22"
    expose:
      - "3000"
    environment:
      - VIRTUAL_HOST=git.bilili.work
      - VIRTUAL_PORT=3000
    depends_on:
      - mysql
    restart: always
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - /data/mysql/:/var/lib/mysql
