version: '2'
services:
  proxy:
    restart: always
    image: jwilder/nginx-proxy:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/certs:/etc/nginx/certs:ro
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./etc/nginx/vhost.d:/etc/nginx/vhost.d
      - ./data/nginx-proxy/html:/usr/share/nginx/html
    ports:
      - "80:80"
      - 443:443
    expose:
      - "80"
  nginx-proxy-le:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: proxy_le
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./etc/nginx/certs:/etc/nginx/certs:rw
  gitserver:
    container_name: 'gitease1'
    image: 'cirocosta/gitserver-http'
    volumes:
      - '/staq/data/git/repos:/var/lib/git'
      - '/staq/data/git/nginx/sites-enabled:/etc/nginx/sites-enabled'
      - '/staq/data/git/htpasswd:/staq/git/htpasswd'
    command:
     - '-start'
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=git.staq.work
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=git.staq.work #证书的域名
      - LETSENCRYPT_EMAIL=yuhaixy@outlook.com #证书所有者的邮箱，快过期时会提醒
  blog:
    container_name: 'typecho1'
    image: staq/typecho:20190101-1
    restart: always
    volumes:
      - /staq/data/typecho/data:/data
      - /staq/data/typecho/uploads:/var/www/html/usr/uploads
      - /staq/data/typecho/themes:/var/www/html/usr/themes
      - /staq/data/typecho/plugins:/var/www/html/usr/plugins
    environment:
      - VIRTUAL_HOST=www.geehack.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=www.geehack.com
      - LETSENCRYPT_ENMAIL=yuhaixy@outlook.com

