version: '2'
services:
  gitlab-web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'git.bilili.work'
    ports:
      - '80:80'
    volumes:
      - '/data/gitlab/config:/etc/gitlab'
      - '/data/gitlab/logs:/var/log/gitlab'
      - '/data/gitlab/data:/var/opt/gitlab'
