version: '3'

services:
  etcd:
    image: 'quay.io/coreos/etcd:v2.3.8'
    restart: always
    ports:
      - "2379:2379"
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd0
      - -data-dir
      - /data/etcd
      - -listen-client-urls
      - http://${HostIP}:2379
      - -initial-advertise-peer-urls
      - http://${HostIP}:2380
      - listen-peer-urls
      - http://0.0.0.0:2380
      - -initial-cluster-token
      - etcd-cluster-1
      - -initial-cluster-state
      - new
    env_file:
      - ./host.env
    volumes:
      - /usr/share/ca-certificates/:/etc/ssl/certs
