version: '3'
services:
  jira:
    image: 'cptactionhank/atlassian-jira'
    restart: always
    hostname: 'p.callme.work'
    ports:
      - '8081:8080'
    environment:
      - X_PROXY_NAME=p.callme.work
      - X_PROXY_PORT=80
      - X_PROXY_SCHEME=http
