version: '2'
services:
  proxy:
    image: jwilder/nginx-proxy:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    expose:
      - "80"
