version: '3'

services:
  cassandra1:
    image: cassandra:3
    container_name: cassandra
    environment:
      - CASSANDRA_SEEDS=172.26.0.15
      - CASSANDRA_BROADCAST_ADDRESS=172.26.0.15
      - CASSANDRA_LISTEN_ADDRESS=172.26.0.15
      - CASSANDRA_CLUSTER_NAME=HUWO_CSDRA_DEV
    ports:
      - 7000:7000
      - 9042:9042
    restart: always
    volumes:
      - /data/cassandra/data:/var/lib/cassandra:rw
