version: '2.0'

services:
  nginx:
    restart: always
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./volumes/conf.d:/etc/nginx/conf.d
      - ./volumes/log:/var/log/nginx
      - ./volumes/www:/var/www
