version: '3'
services:
  mysql:
    container_name: mysql1
    image: mysql:5.7
    volumes:
      - ~/usr/docker/mysql/data:/var/lib/mysql
    ports:
      - "3366:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
