version: '3.1'

services:

  db:
    name: mysql1
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    secrets:
      - mysql_root_password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /staq/data/mysql:/var/lib/mysql


secrets:
  mysql_root_password:
    external: true
